### ISSUE TITLE
zotero 7's policies.json file conflicts with firefox's policies.json

### ISSUE THREAD

**Issue by Suya1671** [camillemndn/zotero-nix#2]
Read the title. I'm using firefox and zotero-nix and the home-manager path fails to build with the following error:

```
error: collision between `/nix/store/rrlgprlzrvycdcywv9l51j9kmhkprfsb-firefox-128.0.3/lib/firefox/distribution/policies.json' and `/nix/store/2pavjqg14ymf1az3j0y5vy5sdzrbdhah-zotero-7.0.0.SOURCE.7e01a7d0e/lib/firefox/distribution/policies.json'
```

**Comment by camillemndn** [comment]
Hi, simply do not override ```firefox-esr``` dependency. Zotero is intended to work with Firefox ESR 115 for now, not 128.

**Comment by Suya1671** [comment]
> Hi, simply do not override `firefox-esr` dependency. Zotero is intended to work with Firefox ESR 115 for now, not 128.

I'm not overriding any dependency. Weird.

**Comment by camillemndn** [comment]
Can you provide any more logs and system info please?

**Comment by camillemndn** [comment]
I close this for now. Feel free to reopen if you need!
